Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: C:\Users\kkalya622\PycharmProjects\AWS_SAM_Project\hello_world
      Runtime: python3.9